spring.application.name=springbootpostgressecurity
# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# DATASOURCES
# ===============================
# Primary database: PostgreSQL
spring.datasource.postgres.url=${POSTGRES_URL:jdbc:postgresql://localhost:5432/springbootpostgressecurity}
spring.datasource.postgres.username=${POSTGRES_USERNAME:postgres}
spring.datasource.postgres.password=${POSTGRES_PASSWORD:postgres}
spring.datasource.postgres.driver-class-name=org.postgresql.Driver

# Secondary database: ClickHouse
app.datasource.clickhouse.url=jdbc:clickhouse://localhost:8123/demo?compress=0
app.datasource.clickhouse.username=${CLICKHOUSE_USERNAME:admin}
app.datasource.clickhouse.password=${CLICKHOUSE_PASSWORD:admin}
app.datasource.clickhouse.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
logging.level.org.flywaydb=DEBUG

# Optional
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# REDIS
# ===============================
spring.data.redis.host=redis
spring.data.redis.port=6379

# ===============================
# JWT
# ===============================
bezkoder.app.jwtSecret=${JWT_SECRET:ZGV2ZWxvcG1lbnQtand0LXNlY3JldC1jaGFuZ2UtbWU=}
bezkoder.app.jwtExpirationMs=86400000
